# Generated by Django 4.1.5 on 2023-02-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('views', models.IntegerField(default=0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('description', models.FileField(blank=True, null=True, upload_to='descriptions/')),
                ('trailer', models.CharField(blank=True, max_length=12, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='imdb.director')),
            ],
        ),
    ]
