# Generated by Django 4.1.5 on 2023-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_useraddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddon',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='user_avatars/'),
        ),
    ]
