# Generated by Django 4.1.5 on 2023-02-11 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imdb', '0006_moviecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
